fix: make libcheck fatal if missing with --with-check
Without this, trying to run `make check` after `configure
--without-check` fails to link:
`undefined reference to `srunner_create'`

Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>